### ISSUE TITLE
Unclear why motif is excluded

### ISSUE THREAD

**Issue by alexweisberg** [cultivarium/MicrobeMod#11]
I've tried running MicrobeMod on a few of my strains and it runs well and the output makes sense. However, in looking at the STREME output and the text produced by MicrobeMod, I don't understand why a few of the motifs are not included in the final output despite having conserved patterns and small e-values. For example, here is the output for one run:

$ MicrobeMod call_methylation -b ../sample01_calls.aligned.sorted.bam -r ../sample01.fna -t 10
23-11-16 14:33:26 INFO     Running modkit: modkit pileup -t 10 ../sample01_calls.aligned.sorted.bam sample01_calls.aligned.sorted_low.bed -r ../sample01.fna --only-tabs --filter-threshold 0.66
23-11-16 14:34:15 INFO     Reading low cutoff Modkit table...
23-11-16 14:34:34 INFO     Retrieving sequences
23-11-16 14:35:05 INFO     Total number of sites with any possible calls (including low quality): 9158475 bases
23-11-16 14:35:05 INFO     Median coverage (stranded): 5.0x
23-11-16 14:35:06 INFO     Total number of sites with greater than min coverage (10x): 394858 bases
23-11-16 14:35:06 INFO     Potential sites (>33%) for methylation type h: 20 bases
23-11-16 14:35:06 INFO     High quality sites (>66%) for methylation type h: 0 bases
23-11-16 14:35:06 INFO     Very high quality sites (>90%) for methylation type h: 0 bases
23-11-16 14:35:06 INFO     Potential sites (>33%) for methylation type m: 178 bases
23-11-16 14:35:06 INFO     High quality sites (>66%) for methylation type m: 70 bases
23-11-16 14:35:06 INFO     Very high quality sites (>90%) for methylation type m: 17 bases
23-11-16 14:35:06 INFO     Potential sites (>33%) for methylation type a: 1816 bases
23-11-16 14:35:06 INFO     High quality sites (>66%) for methylation type a: 422 bases
23-11-16 14:35:06 INFO     Very high quality sites (>90%) for methylation type a: 151 bases
23-11-16 14:35:06 INFO     Running for Methylation type: 6mA
23-11-16 14:35:07 INFO     Modkit table size: 2507775
23-11-16 14:35:07 INFO     151 sites for STREME with cutoff 0.9 and min coverage 10
23-11-16 14:35:07 INFO     Creating background control distribution: sample01_calls.aligned.sorted_a_control.fasta
23-11-16 14:35:08 INFO     Running STREME: streme . --n sample01_calls.aligned.sorted_a_control.fasta -p sample01_calls.aligned.sorted_a_pos.fasta -o sample01_calls.aligned.sorted_a_pos_streme
23-11-16 14:37:36 INFO     Found and trimmed motif: 1-VNBSGAWTCSVNB	GAWTC	1367
23-11-16 14:37:36 INFO     Found and trimmed motif: 2-SGGTGGTGRYGVNBN	GGTGGTG	326
23-11-16 14:37:37 INFO     Found and trimmed motif: 3-KCATGCAGGBBRHB	KCATGCAG	145
23-11-16 14:37:40 INFO     Counting genome sites for: GAWTC
23-11-16 14:37:40 INFO     Motif has 186 methylated instances
23-11-16 14:37:41 INFO     Methylated positions in motif GAWTC:
23-11-16 14:37:41 INFO     2    48.924731
4    48.924731
3     2.150538
Name: count, dtype: float64
23-11-16 14:37:41 INFO     Counting genome sites for: KCATGCAG
23-11-16 14:37:41 INFO     Motif has 37 methylated instances
23-11-16 14:37:41 INFO     Methylated positions in motif KCATGCAG:
23-11-16 14:37:41 INFO     7    100.0
Name: count, dtype: float64
23-11-16 14:37:41 INFO     Running for Methylation type: 5mC
23-11-16 14:37:43 INFO     Modkit table size: 3325350
23-11-16 14:37:43 INFO     17 sites for STREME with cutoff 0.9 and min coverage 10
23-11-16 14:37:43 INFO     Creating background control distribution: sample01_calls.aligned.sorted_m_control.fasta
23-11-16 14:37:43 INFO     Running STREME: streme . --n sample01_calls.aligned.sorted_m_control.fasta -p sample01_calls.aligned.sorted_m_pos.fasta -o sample01_calls.aligned.sorted_m_pos_streme
23-11-16 14:39:02 INFO     Complete!
23-11-16 14:39:02 INFO     Saving methylated site table to: sample01_calls.aligned.sorted_methylated_sites.tsv
23-11-16 14:39:02 INFO     Saving motif output to: sample01_calls.aligned.sorted_motifs.tsv

MicrobeMod reports GAWTC and KCATGCAG as motifs, however the second motif, GGTGGTG, is not reported in the final output:

$ cat sample01_calls.aligned.sorted_motifs.tsv
	index	Motif	Motif_raw	Methylation_type	Genome_sites	Methylated_sites	Methylation_coverage	Average_Percent_Methylation_per_site	Methylated_position_1	Methylated_position_1_percent	Methylated_position_2	Methylated_position_2_percent
0	0	GAWTC	1-VNBSGAWTCSVNB	a	10278	362	0.035	0.79	2	48.925	4	48.925
1	1	KCATGCAG	3-KCATGCAGGBBRHB	a	810	37	0.046	0.89	7	100.0	NA	0
2	2	No Motif Assigned	NA	a	NA	199	NA	0.83	NA	NA	NA	NA
3	0	No Motif Assigned	NA	m	NA	70	NA	0.8	NA	NA	NA	NA 

In the streme output txt this motif has an evalue of 5.2e-007.

Is there another level of filtering that is taking place? Thanks!

**Comment by alexcritschristoph** [comment]
That is interesting, I'm not 100% sure yet.... Are you seeing multiple examples of it across genomes or just this one?

1. So my best guess right now is that `GGTGGTG` is dropped because there is no A or C to be methylated in this motif. This sequence seems somewhat artifactual, I wonder if it is something that occurs nearby a repetitive region in your genome that does contain a methylated A or C.
 
2. I do notice that this genome is at very low coverage and most of your sites will be below the min coverage threshold (your output says this genome's median 5x stranded coverage which is below the default 10x threshold). You could try setting `--min_strand_coverage 5` or even `--min_strand_coverage 3` (as low as I have gone) for this low coverage sample. 

3. I noticed that you added a methylation type `h`.... do you want this to be a regular feature? I am guessing this is 5hmCG? It's a shame there is no all-context 5hmC model.... maybe it will come in the future after 4mC. 

4. Is this a prokaryotic genome or perhaps something else? Do you know if anyone has ever seen 5hmC in a prokaryotic genome? I know it is in T4 phage. 
 
5.  Can you verify the number of sequences that actually mad it into your `sample01_calls.aligned.sorted_a_pos.fasta` file? Do you look to see where these `GGTGGTG` are in there, perhaps downstream of the methylated A or C (which should be central in the each kmer)?

**Comment by alexweisberg** [comment]
Thank you for the responses. This is a bacterial genome. I think the issue here was a mix of a low-coverage genome and the fact that I had included the 5hmC methylation calls. I was originally doing the basecalling with everything to see what Dorado would output, with the 6mA and 5mC_5hmC models. I should have used the 5mC model instead.

When I reran the analysis with another sample with much higher coverage, and with just 5mC and 6mA models, I got results that make sense (2 well supported motifs).

**Comment by alexweisberg** [comment]
Also, I just checked and it appears that the v0.4.0 version of Dorado and later includes an all context 5mC/5hmC model that may be useful (https://github.com/nanoporetech/dorado/releases/tag/v0.4.0). I had originally downloaded this model from rerio. Though I don’t know how common 5hmC is for bacteria outside of replication.

**Comment by alexcritschristoph** [comment]
Oh wow, I see that model now too. I wonder if it is supposed to superceede the all context 5mC. 

I might play around with it and see if we can incorporate it.
