### ISSUE TITLE
Permissions on s3 example files?

### ISSUE THREAD

**Issue by JamesRH** [cultivarium/MicrobeMod#12]
All 3 AWS CLI S3 commands in the readme result in an error for me:

```shell
aws  s3 cp --recursive s3://cultivarium-sequencing/MICROBEMOD-DATA-NOV2023/pod5/ .
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied
```

The flags `--no-sign-request` `--no-verify-ssl` and `--request-payer=requester` did not change the error. 

Other public buckets retrieved without issue for me on the same system. Are these not public or not set up for "requester pays"?

Environment (Ubuntu-like w/ latest aws cli apt-geted):

```shell
 aws --version
aws-cli/1.22.34 Python/3.10.12 Linux/6.5.6-76060506-generic botocore/1.23.34


cat /etc/os-release
NAME="Pop!_OS"
VERSION="22.04 LTS"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 22.04 LTS"
VERSION_ID="22.04"
UBUNTU_CODENAME=jammy
```

**Comment by alexcritschristoph** [comment]
Sorry about that, will address tomorrow.

**Comment by alexcritschristoph** [comment]
Hi, this should be fixed now, are you able to access?

**Comment by JamesRH** [comment]
Yes, thank you, that makes testing easier.
