### ISSUE TITLE
Feature request: support for 4mC motifs with new models

### ISSUE THREAD

**Issue by alexweisberg** [cultivarium/MicrobeMod#13]
Again, thank you very much for developing this tool, it has opened up several exciting new research projects for us.

It looks like Nanopore has just released beta models on rerio that now include 4mC modifications: https://github.com/nanoporetech/rerio (res_dna_r10.4.1_e8.2_400bps_sup@v4.3.0_4mC_5mC@v1). 

I was wondering if MicrobeMod could eventually add support for these and report 4mC motifs as well? 

Thanks!

**Comment by alexcritschristoph** [comment]
Yes, definitely! Will have a brief update that is imminent, and then this is next on the list.

**Comment by alexweisberg** [comment]
Great! Thank you.

**Comment by alexcritschristoph** [comment]
Included in https://github.com/cultivarium/MicrobeMod/pull/14 - let me know how it works for you! Seems to be working for me at the moment.

**Comment by alexweisberg** [comment]
Excellent thank you! I will try out both features. On Dec 31, 2023, at 11:56 AM, Alex Crits-Christoph ***@***.***> wrote:﻿
Closed #13 as completed.

**Comment by alexweisberg** [comment]
I tried it out and its working great for 4mC data. Thanks!

**Comment by galenptacek** [comment]
@Ge0rges modkit refers to 4mC by its ChEBI code (21839). 

can refer to line 20 in microbemod.py:
METHYLATION_TYPES = {"6mA": "a", "5mC": "m", "4mC": "21839", "5hmC": "h"}
