### ISSUE TITLE
Support for 4khz Nanopore data

### ISSUE THREAD

**Issue by 09herbej** [cultivarium/MicrobeMod#15]
Hi! Currently the Dorado models for this programme are only for 5khz data, I can only call 5mC for my data - I wondered whether I could still use the programme or if it only works for 5khz data with 6mA called as well? Thanks!

**Comment by alexcritschristoph** [comment]
Hi! Apologies for my slow response.

The good news is that you can use MicrobeMod with 4 kHz data - in fact, we did this for some of our data in the preprint, as the switch to 5 kHz only happened partway through this year.


As you note, Dorado is only listing 5 kHz models at the moment; however, you can still download the 4 kHz models through remora and pass them to Dorado:
https://github.com/nanoporetech/remora

try:
```
remora model list_pretrained
```

And you'll see some 4 kHz models listed. Download these and pass them to dorado and the resulting BAM should be readable with MicrobeMod.

**Comment by alexcritschristoph** [comment]
Follow-up, if you only have 5mC and not 6mA calls in your data that should work fine (shouldn't give a bug - let me know if it does)
