### ISSUE TITLE
MAGs

### ISSUE THREAD

**Issue by Thexiyang** [cultivarium/MicrobeMod#16]
Thanks for this nice tool! Does this tool work also metagenome-assembled data from PB and Nanopore?

**Comment by alexcritschristoph** [comment]
So this should work with MAGs, but I would feed it one MAG (or contig, if you have a big contig say for a viral genome) as a genome at a time.
It will not work for PacBio data unfortunately, only R10+ Nanopore data as it expects a BAM that can be read by ModKit:
https://github.com/nanoporetech/modkit
