### ISSUE TITLE
Matching prodigal call with methylation location

### ISSUE THREAD

**Issue by Ge0rges** [cultivarium/MicrobeMod#17]
Hello,

It would be an interesting feature if the tool could use the prodigal output and methylation location to tell us, for example, if the promoter region is methylated, or if the methylation location is coding or non coding. 

I think this would be specifically interesting in the analysis of differentially methylated regions (instead of consistently methylated motifs) where DNA methylation may play a role in gene expression. This could also be the place to link with methyltransferases that are found in `annotate_rm` but not associated with an rm system.

**Comment by alexcritschristoph** [comment]
I do think that would be cool. Because our focus is mostly on RM and not roles for methylation in gene regulation, I don't plan to add this in the near term, so for the time being people will have to parse that result from the _sites table and their prodigal gff and analyze in the way they see fit.
