### ISSUE TITLE
Significance of identified motifs?

### ISSUE THREAD

**Issue by starkeynight** [cultivarium/MicrobeMod#20]
Hello,

I am curious about the outputs from call_methylation. Are identified motifs determined based on a pre-set list of possible motifs, or are they identified based simply on the sequences? (I.e. - is this de novo methylation motif detection?)

If available, it would be useful to know if there is a list of possible methylation motifs that can be detected.

Thanks!

**Comment by alexcritschristoph** [comment]
I have good news for you: all motifs are identified de novo from the methylated sites. There is no apriori list, only rules are they have to be between 3 and 26 bp long.

**Comment by starkeynight** [comment]
Fantastic! Thank you very much :)
