### ISSUE TITLE
Reference genomes no longer available

### ISSUE THREAD

**Issue by MarkusHaak** [cultivarium/MicrobeMod#25]
Hi,
I noticed that the folder reference_genomes is no longer available in the aws bucket. Could you re-upload the data or supply an alternative link? Thank you very much!

Markus

**Comment by alexcritschristoph** [comment]
Hi Markus,
Sorry about that mistake! They should be available again at the S3 link. And also on NCBI:
https://www.ncbi.nlm.nih.gov/bioproject/PRJNA1037563/

Thanks!
Alex
