### ISSUE TITLE
Error at the final step

### ISSUE THREAD

**Issue by ATVincent** [cultivarium/MicrobeMod#30]
Hello,

I recently installed MicrobeMod (the pytest revealed no problems). I'm following the tutorial step by step with my data and I get a problem at what I think is the last step of the pipeline:

**MicrobeMod call_methylation -b KHSMHJ_1_pod5.mapped.bam -r KHSMHJ_1_KG925.fna -t 30**

24-12-11 14:43:18 INFO     Running modkit: modkit pileup -t 30 KHSMHJ_1_pod5.mapped.bam KHSMHJ_1_KG925_low.bed -r KHSMHJ_1_KG925.fna --only-tabs --filter-threshold 0.66
24-12-11 14:45:00 INFO     Reading Modkit table...
24-12-11 14:45:03 INFO     Retrieving sequences
24-12-11 14:45:08 INFO     Total number of sites with any possible calls (including low quality): 4380727 bases
24-12-11 14:45:08 INFO     Median coverage (stranded): 388.0x
24-12-11 14:45:08 INFO     Total number of sites with greater than min coverage (10x): 4380724 bases
24-12-11 14:45:09 INFO     Potential sites (>33%) for methylation type m: 72 bases
24-12-11 14:45:09 INFO     High quality sites (>66%) for methylation type m: 4 bases
24-12-11 14:45:09 INFO     Very high quality sites (>90%) for methylation type m: 0 bases
24-12-11 14:45:09 INFO     Potential sites (>33%) for methylation type 21839: 1578 bases
24-12-11 14:45:09 INFO     High quality sites (>66%) for methylation type 21839: 101 bases
24-12-11 14:45:09 INFO     Very high quality sites (>90%) for methylation type 21839: 0 bases
24-12-11 14:45:09 INFO     Potential sites (>33%) for methylation type a: 25943 bases
24-12-11 14:45:09 INFO     High quality sites (>66%) for methylation type a: 20944 bases
24-12-11 14:45:09 INFO     Very high quality sites (>90%) for methylation type a: 14245 bases
24-12-11 14:45:09 INFO     Running for Methylation type: 6mA
24-12-11 14:45:09 INFO     Modkit table size: 1892995
24-12-11 14:45:09 INFO     14245 sites for STREME with cutoff 0.9 and min coverage 10
24-12-11 14:45:10 INFO     Creating background control distribution: KHSMHJ_1_KG925_a_control.fasta
24-12-11 14:45:10 INFO     Running STREME: streme . --n KHSMHJ_1_KG925_a_control.fasta -p KHSMHJ_1_KG925_a_pos.fasta -o KHSMHJ_1_KG925_a_pos_streme
Traceback (most recent call last):
  File "/zfs-hdd/Antony/miniconda3/envs/MicrobeMod_env/bin/MicrobeMod", line 220, in <module>
    microbemod.main(
  File "/zfs-hdd/Antony/miniconda3/envs/MicrobeMod_env/lib/python3.9/site-packages/MicrobeMod/microbemod.py", line 557, in main
    modkit_table_tmp = assign_motifs(
  File "/zfs-hdd/Antony/miniconda3/envs/MicrobeMod_env/lib/python3.9/site-packages/MicrobeMod/microbemod.py", line 295, in assign_motifs
    evalue = float(motif.get("test_evalue"))
TypeError: float() argument must be a string or a number, not 'NoneType'

Do you have any ideas for solving the problem? Thank you and have a nice day!

**Comment by alexcritschristoph** [comment]
I think this is a streme version issue - what version are you using? Test it with `streme --version`.

If you're using an older version of streme than 5.4.1 or 5.5, try upgrading to those - if you're using a newer version, let me know the version and I'll see if I can update to work with it.

**Comment by ATVincent** [comment]
Hello,
I upgraded the streme version and the problem is solved. Thank you for this excellent tool and the quick response.
