### ISSUE TITLE
HMM gene coverage

### ISSUE THREAD

**Issue by Ge0rges** [cultivarium/MicrobeMod#4]
Hello,

You look for and identify RM genes by using `hmmer` with HMMs from Defense Finder (for type 1,2,3,4 systems), and a set of 12 HMMs from PFAM. You then assign REBASE homology to the significant hits using BLAST.

I was wondering if your selection of HMMs cover as many prokaryotic genes as are identified in REBASE? I ask because I notice that you do not use an HMM built from the REBASE database itself, which you state is the most comprehensive.

**Comment by alexcritschristoph** [comment]
I think the [HMMs from DefenseFinder](https://github.com/mdmparis/defense-finder) are pretty sensitive for this. As a quick check, they hit 93% of all proteins in REBASE. I actually have no idea how REBASE does their enzyme annotation, but it's not necessarily a ground-truth into itself in that regard.
