### ISSUE TITLE
support for previously annotated genome in annotate_rm

### ISSUE THREAD

**Issue by alexweisberg** [cultivarium/MicrobeMod#5]
Hi, this tool looks fantastic and should be a great resource. Thanks for developing it. 

I was looking at the annotate_rm tool and it seems like it could be sped up if it supported a user-supplied annotated genome (i.e. from bakta or prokka) in gbk or gff3 format as input. That way it would not need to annotate ORFs with prodigal. This would also provide the benefit of linking the RM loci to known locus tags.

This isn't necessary but it could be a useful feature. Thanks!

**Comment by alexcritschristoph** [comment]
Definitely, will work on this soon. Is GenBank or GFF3 preferred from your perspective?

**Comment by alexweisberg** [comment]
I know people differ on preferences on this but I think GenBank is typically easier as the format is more consistent, and it always includes the nucleotide sequence as well.

Alex

**Comment by alexcritschristoph** [comment]
Included in https://github.com/cultivarium/MicrobeMod/pull/14 - let me know if there are any issues!
