### ISSUE TITLE
tags/release

### ISSUE THREAD

**Issue by jowodo** [cultivarium/MicrobeMod#6]
Hi, 

I think that a tag and release would be really nice to increase reproducibility. 

Thanks

**Comment by jowodo** [comment]
creating tags in github is very easy: https://stackoverflow.com/questions/18216991/create-a-tag-in-a-github-repository/18223354#18223354
The version could be 0.0.0 
What do you think?

**Comment by alexcritschristoph** [comment]
Yes, good idea, will do.

**Comment by alexcritschristoph** [comment]
Included in https://github.com/cultivarium/MicrobeMod/pull/14
